language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=dd3958657f6e509bafac49dfdf0430431b80aba0b0affc00e381709b6d2d1b7b
  matrix:
    include:
      - node_js: '12'
  cache:
    directories: [node_modules]
  install:
    yarn
  after_success: yarn coverage
  before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
  script:
    - yarn test
  after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESTFUL